### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by lencx** [kamranahmedse/githunt#42]
```css
.grid-item-container .repo-body p {
    font-size: 14px;
    margin-bottom: 0;
    color: #6e7583;
    word-break: break-all; // + add
}
```

<img width="508" alt="Screen Shot 2019-10-19 at 16 37 11" src="https://user-images.githubusercontent.com/16164244/67140801-d1c3e700-f290-11e9-831b-15ae2c5decd2.png">
